# === PRODUCTION PROFILE (DigitalOcean) ===
spring:
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

server:
  port: ${PORT:8081}
